apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: hello-world-api
  labels:
    app: api
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: api
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi

---

apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: hello-world-api
spec:
  ports:
  - port: 8888
    targetPort: 8888
  selector:
    app: api

