# doc: https://skaffold.dev/docs/references/yaml
apiVersion: skaffold/v2beta29
kind: Config

build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: api
      context: .
      docker:
        dockerfile: api/Dockerfile
    - image: rpc
      context: .
      docker:
        dockerfile: rpc/Dockerfile

deploy:
  kubectl:
    manifests:
    - api/k8s/*
    - rpc/k8s/*

portForward:
  - resourceType: service
    resourceName: api-svc
    namespace: hello-world-api
    port: 8888
    localPort: 8888